[lab1] Berebenia
dinamio/MF-Angular pull request #13
Opened 2017-10-26 06:38 UTC by julialbe

My first attempt work with Angular JS.
Appreciate any comments.

2017-10-26 06:41 UTC, julialbe commented
@dinamio Имеет смысл смотреть только второй коммит 950390c05635d12cc00bf680fa927be68d36f06f, первый это мусор от IDE

2017-10-29 12:23 UTC, dinamio requested changes
Please, add node_modules to .gitgnore, 26813 files are too much)

2017-11-24 10:56 UTC, dinamio commented
Первый коммит все еще будет включен в итоговую версию, поэтом node_modules определенно должны быть в .gitignore.

2017-12-13 19:44 UTC, julialbe commented
@dinamio проаммендила первый коммит, папки как и не бывало

2017-12-13 19:46 UTC, dinamio approved these changes
Так намного лучше

2017-12-13 19:47 UTC, merged